name: login_register_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  spider: ^4.2.2
  change_app_package_name: ^1.2.0
  page_transition: ^2.1.0
  audioplayers: ^6.0.0
  just_audio: ^0.9.38
  audio_service: ^0.18.13
  just_audio_background: ^0.0.1-beta.12
  rxdart: ^0.27.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/
    - assets/gaz/
    - assets/songs/
